version: "3.8" # lastest version as of now

services:
  web:
    build: . # build from root Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 # django local server port
    volumes:
      - .:/code # mount current dir to /code in the container
    ports:
      - "8000:8000" # connect local port 8000 with container's 8000
    environment: # connect web app with db using same credentials.
      - POSTGRES_NAME=xyz-main
      - POSTGRES_USER=xyzAdmin
      - POSTGRES_PASSWORD=gDmuZQPg!Einps2mqPCy
    depends_on:
      - db
  db:
    image: postgres # lastest postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data # local db volumne mount
    environment: # sample credentials
      - POSTGRES_DB=xyz-main
      - POSTGRES_USER=xyzAdmin
      - POSTGRES_PASSWORD=gDmuZQPg!Einps2mqPCy